# Distrobox defaults
DBX_CONTAINER_ALWAYS_PULL=0
DBX_CONTAINER_GENERATE_ENTRY=1
DBX_CONTAINER_HOME_PREFIX="$HOME/.containers"
DBX_CONTAINER_INIT_HOOK=""
DBX_CONTAINER_MANAGER="podman"
DBX_EXPORT_PATH="$HOME/.local/bin"
